[package]
name = "bevis"
version = "0.1.0"
edition = "2021"
authors = ["Mathias Hall-Andersen"]

[dependencies]
bevis_derive = { path = "bevis_derive" }
serde = {version = "1", optional = true}

[features]
default = ["serde", "alloc"]
serde = ["dep:serde"]
alloc = []

[dev-dependencies]
serde = "1" 
compiletest_rs = "0.9"