name: CI

on: [push, pull_request]

jobs:
  bevis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, nightly]

    steps:
      - uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          default: true
          toolchain: ${{ matrix.toolchain }}

      - name: Update local toolchain
        run: |
          rustup component add clippy
          rustup component add rustfmt
          rustup update

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Test
        run: |
          cargo check
          cargo test --all

      - name: Build Release
        run: |
          cargo build --release
